const energy = {
    metric: {
        J: { name: { singular: 'Joule', plural: 'Joules' }, to_anchor: 1 },
        kJ: { name: { singular: 'Kilojoule', plural: 'Kilojoules' }, to_anchor: 1000 },
        kW_h: { name: { singular: 'Kilowatt-hour', plural: 'Kilowatt-hours' }, to_anchor: 3600000 },
        W_h: { name: { singular: 'Watt-hour', plural: 'Watt-hours' }, to_anchor: 3600 },
        cal: { name: { singular: 'Calorie (nutritional)', plural: 'Calories (nutritional)' }, to_anchor: 4.184 },
        hp_h: { name: { singular: 'Horsepower hour', plural: 'Horsepower hours' }, to_anchor: 2684519.54 },
        Btu_IT: { name: { singular: 'Btu (IT)', plural: 'Btu (IT)' }, to_anchor: 1055.06 },
        Btu_th: { name: { singular: 'Btu (th)', plural: 'Btu (th)' }, to_anchor: 1054.35 },
        GJ: { name: { singular: 'Gigajoule', plural: 'Gigajoules' }, to_anchor: 1e9 },
        MJ: { name: { singular: 'Megajoule', plural: 'Megajoules' }, to_anchor: 1e6 },
        mJ: { name: { singular: 'Millijoule', plural: 'Millijoules' }, to_anchor: 0.001 },
        µJ: { name: { singular: 'Microjoule', plural: 'Microjoules' }, to_anchor: 1e-6 },
        nJ: { name: { singular: 'Nanojoule', plural: 'Nanojoules' }, to_anchor: 1e-9 },
        aJ: { name: { singular: 'Attojoule', plural: 'Attojoules' }, to_anchor: 1e-18 },
        MeV: { name: { singular: 'Megaelectron-volt', plural: 'Megaelectron-volts' }, to_anchor: 1.60218e-13 },
        keV: { name: { singular: 'Kiloelectron-volt', plural: 'Kiloelectron-volts' }, to_anchor: 1.60218e-16 },
        eV: { name: { singular: 'Electron-volt', plural: 'Electron-volts' }, to_anchor: 1.60218e-19 },
        erg: { name: { singular: 'Erg', plural: 'Ergs' }, to_anchor: 1e-7 }
    },
    imperial: {
        GW_h: { name: { singular: 'Gigawatt-hour', plural: 'Gigawatt-hours' }, to_anchor: 3.6e12 },
        MW_h: { name: { singular: 'Megawatt-hour', plural: 'Megawatt-hours' }, to_anchor: 3.6e9 },
        kW_s: { name: { singular: 'Kilowatt-second', plural: 'Kilowatt-seconds' }, to_anchor: 1000 },
        W_s: { name: { singular: 'Watt-second', plural: 'Watt-seconds' }, to_anchor: 1 },
        N_m: { name: { singular: 'Newton meter', plural: 'Newton meters' }, to_anchor: 1 },
        hp_h: { name: { singular: 'Horsepower hour', plural: 'Horsepower hours' }, to_anchor: 2684519.54 },
        kcal_IT: { name: { singular: 'Kilocalorie (IT)', plural: 'Kilocalories (IT)' }, to_anchor: 4184 },
        kcal_th: { name: { singular: 'Kilocalorie (th)', plural: 'Kilocalories (th)' }, to_anchor: 4186.8 },
        cal_IT: { name: { singular: 'Calorie (IT)', plural: 'Calories (IT)' }, to_anchor: 4.184 },
        cal_th: { name: { singular: 'Calorie (th)', plural: 'Calories (th)' }, to_anchor: 4.1868 },
        MBtu_IT: { name: { singular: 'Mega Btu (IT)', plural: 'Mega Btu (IT)' }, to_anchor: 1055055852.62 },
        Ton_hr: { name: { singular: 'Ton-hour (refrigeration)', plural: 'Ton-hours (refrigeration)' }, to_anchor: 12000 },
        J__kl: { name: { singular: 'Fuel oil equivalent @ kiloliter', plural: 'Fuel oil equivalent @ kiloliter' }, to_anchor: 39600000000 },
        J__barrel: { name: { singular: 'Fuel oil equivalent @ barrel (US)', plural: 'Fuel oil equivalent @ barrels (US)' }, to_anchor: 6117860000 },
        Gton: { name: { singular: 'Gigaton', plural: 'Gigatons' }, to_anchor: 1e18 },
        Mton: { name: { singular: 'Megaton', plural: 'Megatons' }, to_anchor: 1e15 },
        kton: { name: { singular: 'Kiloton', plural: 'Kilotons' }, to_anchor: 1e12 },
        ton_exp: { name: { singular: 'Ton (explosives)', plural: 'Tons (explosives)' }, to_anchor: 4.184e9 },
        dyn_cm: { name: { singular: 'Dyne centimeter', plural: 'Dyne centimeters' }, to_anchor: 1e-7 },
        gf_m: { name: { singular: 'Gram-force meter', plural: 'Gram-force meters' }, to_anchor: 0.00980665 },
        gf_cm: { name: { singular: 'Gram-force centimeter', plural: 'Gram-force centimeters' }, to_anchor: 9.80665 },
        kgf_cm: { name: { singular: 'Kilogram-force centimeter', plural: 'Kilogram-force centimeters' }, to_anchor: 98.0665 },
        kgf_m: { name: { singular: 'Kilogram-force meter', plural: 'Kilogram-force meters' }, to_anchor: 9.80665 },
        kp_m: { name: { singular: 'Kilopond meter', plural: 'Kilopond meters' }, to_anchor: 9.80665 },
        lbf_ft: { name: { singular: 'Pound-force foot', plural: 'Pound-force feet' }, to_anchor: 1.35582 },
        lbf_in: { name: { singular: 'Pound-force inch', plural: 'Pound-force inches' }, to_anchor: 0.112984 },
        ozf_in: { name: { singular: 'Ounce-force inch', plural: 'Ounce-force inches' }, to_anchor: 0.00706155 },
        ft_lbf: { name: { singular: 'Foot-pound', plural: 'Foot-pounds' }, to_anchor: 1.35582 },
        in_lbf: { name: { singular: 'Inch-pound', plural: 'Inch-pounds' }, to_anchor: 0.112984 },
        in_ozf: { name: { singular: 'Inch-ounce', plural: 'Inch-ounces' }, to_anchor: 0.00706155 },
        pdl_ft: { name: { singular: 'Poundal foot', plural: 'Poundal feet' }, to_anchor: 0.0421401 },
        therm: { name: { singular: 'Therm', plural: 'Therms' }, to_anchor: 105480400 },
        therm_EC: { name: { singular: 'Therm (EC)', plural: 'Therms (EC)' }, to_anchor: 105505600 },
        therm_US: { name: { singular: 'Therm (US)', plural: 'Therms (US)' }, to_anchor: 105480400 }
    },
    _anchors: {
        metric: { unit: 'J', ratio: 1 },
        imperial: { unit: 'cal_IT', ratio: 4.184 }
    }
};

export default energy;
