const fuelConsumption = {
    metric: {
        'm/L': { name: { singular: 'Meter per Liter', plural: 'Meters per Liter' }, to_anchor: 1 },
        'Em/L': { name: { singular: 'Exameter per Liter', plural: 'Exameters per Liter' }, to_anchor: 1e18 },
        'Pm/L': { name: { singular: 'Petameter per Liter', plural: 'Petameters per Liter' }, to_anchor: 1e15 },
        'Tm/L': { name: { singular: 'Terameter per Liter', plural: 'Terameters per Liter' }, to_anchor: 1e12 },
        'Gm/L': { name: { singular: 'Gigameter per Liter', plural: 'Gigameters per Liter' }, to_anchor: 1e9 },
        'Mm/L': { name: { singular: 'Megameter per Liter', plural: 'Megameters per Liter' }, to_anchor: 1e6 },
        'km/L': { name: { singular: 'Kilometer per Liter', plural: 'Kilometers per Liter' }, to_anchor: 1e3 },
        'hm/L': { name: { singular: 'Hectometer per Liter', plural: 'Hectometers per Liter' }, to_anchor: 1e2 },
        'dam/L': { name: { singular: 'Dekameter per Liter', plural: 'Dekameters per Liter' }, to_anchor: 1e1 },
        'cm/L': { name: { singular: 'Centimeter per Liter', plural: 'Centimeters per Liter' }, to_anchor: 1e-2 },
        'mi/L': { name: { singular: 'Mile (US) per Liter', plural: 'Miles (US) per Liter' }, to_anchor: 1609.34 },
        'n.mile/L': { name: { singular: 'Nautical Mile per Liter', plural: 'Nautical Miles per Liter' }, to_anchor: 1852 },
        'n.mile/gallon (US)': { name: { singular: 'Nautical Mile per Gallon (US)', plural: 'Nautical Miles per Gallon (US)' }, to_anchor: 1 / 0.00378541 },
        'km/gallon (US)': { name: { singular: 'Kilometer per Gallon (US)', plural: 'Kilometers per Gallon (US)' }, to_anchor: 1 / 0.00378541 },
        'm/gallon (US)': { name: { singular: 'Meter per Gallon (US)', plural: 'Meters per Gallon (US)' }, to_anchor: 1 / 0.00378541 },
        'm/gallon (UK)': { name: { singular: 'Meter per Gallon (UK)', plural: 'Meters per Gallon (UK)' }, to_anchor: 1 / 0.00454609 },
        'mi/gallon (US)': { name: { singular: 'Mile (US) per Gallon (US)', plural: 'Miles (US) per Gallon (US)' }, to_anchor: 1 / 0.00378541 },
        'mi/gallon (UK)': { name: { singular: 'Mile (UK) per Gallon (UK)', plural: 'Miles (UK) per Gallon (UK)' }, to_anchor: 1 / 0.00454609 },
        'm/m^3': { name: { singular: 'Meter per Cubic Meter', plural: 'Meters per Cubic Meter' }, to_anchor: 1 },
        'm/cm^3': { name: { singular: 'Meter per Cubic Centimeter', plural: 'Meters per Cubic Centimeter' }, to_anchor: 1e6 },
        'm/yd^3': { name: { singular: 'Meter per Cubic Yard', plural: 'Meters per Cubic Yard' }, to_anchor: 0.764554857984 },
        'm/ft^3': { name: { singular: 'Meter per Cubic Foot', plural: 'Meters per Cubic Foot' }, to_anchor: 35.3147 },
        'm/in^3': { name: { singular: 'Meter per Cubic Inch', plural: 'Meters per Cubic Inch' }, to_anchor: 61023.7 },
        'm/quart (US)': { name: { singular: 'Meter per Quart (US)', plural: 'Meters per Quart (US)' }, to_anchor: 1 / 0.946353 },
        'm/quart (UK)': { name: { singular: 'Meter per Quart (UK)', plural: 'Meters per Quart (UK)' }, to_anchor: 1 / 1.13652 },
        'm/pt (US)': { name: { singular: 'Meter per Pint (US)', plural: 'Meters per Pint (US)' }, to_anchor: 1 / 0.473176 },
        'm/pt (UK)': { name: { singular: 'Meter per Pint (UK)', plural: 'Meters per Pint (UK)' }, to_anchor: 1 / 0.568261 },
        'm/cup (US)': { name: { singular: 'Meter per Cup (US)', plural: 'Meters per Cup (US)' }, to_anchor: 1 / 0.24 },
        'm/cup (UK)': { name: { singular: 'Meter per Cup (UK)', plural: 'Meters per Cup (UK)' }, to_anchor: 1 / 0.284131 },
        'm/fl.ounce (US)': { name: { singular: 'Meter per Fluid Ounce (US)', plural: 'Meters per Fluid Ounce (US)' }, to_anchor: 1 / 0.0295735 },
        'm/fl.ounce (UK)': { name: { singular: 'Meter per Fluid Ounce (UK)', plural: 'Meters per Fluid Ounce (UK)' }, to_anchor: 1 / 0.0284131 },
        'L/m': { name: { singular: 'Liter per Meter', plural: 'Liters per Meter' }, to_anchor: 1 },
        'L/100 km': { name: { singular: 'Liter per 100 Kilometers', plural: 'Liters per 100 Kilometers' }, to_anchor: 100 },
        'gallon (US)/mile': { name: { singular: 'Gallon (US) per Mile', plural: 'Gallons (US) per Mile' }, to_anchor: 1 / 1609.34 },
        'gallon (US)/100 mi': { name: { singular: 'Gallon (US) per 100 Miles', plural: 'Gallons (US) per 100 Miles' }, to_anchor: 100 / 1609.34 },
        'gallon (UK)/mile': { name: { singular: 'Gallon (UK) per Mile', plural: 'Gallons (UK) per Mile' }, to_anchor: 1 / 1609.34 },
        'gallon (UK)/100 mi': { name: { singular: 'Gallon (UK) per 100 Miles', plural: 'Gallons (UK) per 100 Miles' }, to_anchor: 100 / 1609.34 },
    },
    imperial: {
        'mile/gallon (US)': { name: { singular: 'Mile (US) per Gallon', plural: 'Miles (US) per Gallon' }, to_anchor: 1 / 0.00378541 },
        'mile/gallon (UK)': { name: { singular: 'Mile (UK) per Gallon', plural: 'Miles (UK) per Gallon' }, to_anchor: 1 / 0.00454609 },
        'nautical mile/gallon (US)': { name: { singular: 'Nautical Mile (US) per Gallon', plural: 'Nautical Miles (US) per Gallon' }, to_anchor: 1 / 0.00378541 },
        'nautical mile/gallon (UK)': { name: { singular: 'Nautical Mile (UK) per Gallon', plural: 'Nautical Miles (UK) per Gallon' }, to_anchor: 1 / 0.00454609 },
        'meter/quart (US)': { name: { singular: 'Meter per Quart (US)', plural: 'Meters per Quart (US)' }, to_anchor: 1 / 0.946353 },
        'meter/quart (UK)': { name: { singular: 'Meter per Quart (UK)', plural: 'Meters per Quart (UK)' }, to_anchor: 1 / 1.13652 },
        'meter/pint (US)': { name: { singular: 'Meter per Pint (US)', plural: 'Meters per Pint (US)' }, to_anchor: 1 / 0.473176 },
        'meter/pint (UK)': { name: { singular: 'Meter per Pint (UK)', plural: 'Meters per Pint (UK)' }, to_anchor: 1 / 0.568261 },
        'meter/cup (US)': { name: { singular: 'Meter per Cup (US)', plural: 'Meters per Cup (US)' }, to_anchor: 1 / 0.24 },
        'meter/cup (UK)': { name: { singular: 'Meter per Cup (UK)', plural: 'Meters per Cup (UK)' }, to_anchor: 1 / 0.284131 },
        'meter/fl.ounce (US)': { name: { singular: 'Meter per Fluid Ounce (US)', plural: 'Meters per Fluid Ounce (US)' }, to_anchor: 1 / 0.0295735 },
        'meter/fl.ounce (UK)': { name: { singular: 'Meter per Fluid Ounce (UK)', plural: 'Meters per Fluid Ounce (UK)' }, to_anchor: 1 / 0.0284131 },
    },
    _anchors: {
        metric: { unit: 'm/L', ratio: 1 },
        imperial: { unit: 'mile/gallon (US)', ratio: 1 / 0.00378541 }, // Default to miles per gallon (US)
    }
};

export default fuelConsumption;
