const power = {
    metric: {
        W: { name: { singular: 'Watt', plural: 'Watts' }, to_anchor: 1 },
        EW: { name: { singular: 'Exawatt', plural: 'Exawatts' }, to_anchor: 1e18 },
        PW: { name: { singular: 'Petawatt', plural: 'Petawatts' }, to_anchor: 1e15 },
        TW: { name: { singular: 'Terawatt', plural: 'Terawatts' }, to_anchor: 1e12 },
        GW: { name: { singular: 'Gigawatt', plural: 'Gigawatts' }, to_anchor: 1e9 },
        MW: { name: { singular: 'Megawatt', plural: 'Megawatts' }, to_anchor: 1e6 },
        kW: { name: { singular: 'Kilowatt', plural: 'Kilowatts' }, to_anchor: 1000 },
        hW: { name: { singular: 'Hectowatt', plural: 'Hectowatts' }, to_anchor: 100 },
        daW: { name: { singular: 'Dekawatt', plural: 'Dekawatts' }, to_anchor: 10 },
        dW: { name: { singular: 'Deciwatt', plural: 'Deciwatts' }, to_anchor: 0.1 },
        cW: { name: { singular: 'Centiwatt', plural: 'Centiwatts' }, to_anchor: 0.01 },
        mW: { name: { singular: 'Milliwatt', plural: 'Milliwatts' }, to_anchor: 0.001 },
        µW: { name: { singular: 'Microwatt', plural: 'Microwatts' }, to_anchor: 1e-6 },
        nW: { name: { singular: 'Nanowatt', plural: 'Nanowatts' }, to_anchor: 1e-9 },
        pW: { name: { singular: 'Picowatt', plural: 'Picowatts' }, to_anchor: 1e-12 },
        fW: { name: { singular: 'Femtowatt', plural: 'Femtowatts' }, to_anchor: 1e-15 },
        aW: { name: { singular: 'Attowatt', plural: 'Attowatts' }, to_anchor: 1e-18 },
        hp: { name: { singular: 'Horsepower', plural: 'Horsepower' }, to_anchor: 745.7 },
        hp_UK: { name: { singular: 'Horsepower (UK)', plural: 'Horsepower (UK)' }, to_anchor: 745.7 },
        hp_550: { name: { singular: 'Horsepower (550 ft*lbf/s)', plural: 'Horsepower (550 ft*lbf/s)' }, to_anchor: 745.7 },
        hp_metric: { name: { singular: 'Horsepower (metric)', plural: 'Horsepower (metric)' }, to_anchor: 735.499 },
        hp_boiler: { name: { singular: 'Horsepower (boiler)', plural: 'Horsepower (boiler)' }, to_anchor: 9809.5 },
        hp_electric: { name: { singular: 'Horsepower (electric)', plural: 'Horsepower (electric)' }, to_anchor: 746 },
        hp_water: { name: { singular: 'Horsepower (water)', plural: 'Horsepower (water)' }, to_anchor: 746.043 },
        ps: { name: { singular: 'Pferdestarke (ps)', plural: 'Pferdestarkes (ps)' }, to_anchor: 735.499 },
        Btu_h: { name: { singular: 'Btu (IT)/hour', plural: 'Btu (IT)/hour' }, to_anchor: 0.293071 },
        Btu_min: { name: { singular: 'Btu (IT)/minute', plural: 'Btu (IT)/minute' }, to_anchor: 17.5843 },
        Btu_s: { name: { singular: 'Btu (IT)/second', plural: 'Btu (IT)/second' }, to_anchor: 1055.06 },
        Btu_th_h: { name: { singular: 'Btu (th)/hour', plural: 'Btu (th)/hour' }, to_anchor: 0.293071 },
        Btu_th_min: { name: { singular: 'Btu (th)/minute', plural: 'Btu (th)/minute' }, to_anchor: 17.5843 },
        Btu_th_s: { name: { singular: 'Btu (th)/second', plural: 'Btu (th)/second' }, to_anchor: 1055.06 },
        MBtu_h: { name: { singular: 'MBtu (IT)/hour', plural: 'MBtu (IT)/hour' }, to_anchor: 293.071 },
        MBH: { name: { singular: 'MBH', plural: 'MBH' }, to_anchor: 293.071 },
        ton_refrigeration: { name: { singular: 'Ton (refrigeration)', plural: 'Tons (refrigeration)' }, to_anchor: 12000 },
        kcal_h: { name: { singular: 'Kilocalorie (IT)/hour', plural: 'Kilocalories (IT)/hour' }, to_anchor: 1.163 },
        kcal_min: { name: { singular: 'Kilocalorie (IT)/minute', plural: 'Kilocalories (IT)/minute' }, to_anchor: 69.78 },
        kcal_s: { name: { singular: 'Kilocalorie (IT)/second', plural: 'Kilocalories (IT)/second' }, to_anchor: 4186.8 },
        kcal_th_h: { name: { singular: 'Kilocalorie (th)/hour', plural: 'Kilocalories (th)/hour' }, to_anchor: 1.163 },
        kcal_th_min: { name: { singular: 'Kilocalorie (th)/minute', plural: 'Kilocalories (th)/minute' }, to_anchor: 69.78 },
        kcal_th_s: { name: { singular: 'Kilocalorie (th)/second', plural: 'Kilocalories (th)/second' }, to_anchor: 4186.8 },
        cal_h: { name: { singular: 'Calorie (IT)/hour', plural: 'Calories (IT)/hour' }, to_anchor: 0.001163 },
        cal_min: { name: { singular: 'Calorie (IT)/minute', plural: 'Calories (IT)/minute' }, to_anchor: 0.06978 },
        cal_s: { name: { singular: 'Calorie (IT)/second', plural: 'Calories (IT)/second' }, to_anchor: 4.1868 },
        cal_th_h: { name: { singular: 'Calorie (th)/hour', plural: 'Calories (th)/hour' }, to_anchor: 0.001163 },
        cal_th_min: { name: { singular: 'Calorie (th)/minute', plural: 'Calories (th)/minute' }, to_anchor: 0.06978 },
        cal_th_s: { name: { singular: 'Calorie (th)/second', plural: 'Calories (th)/second' }, to_anchor: 4.1868 },
        ft_lbf_h: { name: { singular: 'Foot pound-force/hour', plural: 'Foot pound-force/hour' }, to_anchor: 0.000376616 },
        ft_lbf_min: { name: { singular: 'Foot pound-force/minute', plural: 'Foot pound-force/minute' }, to_anchor: 0.0225969 },
        ft_lbf_s: { name: { singular: 'Foot pound-force/second', plural: 'Foot pound-force/second' }, to_anchor: 1.35582 },
        lbf_ft_h: { name: { singular: 'Pound-foot/hour', plural: 'Pound-foot/hour' }, to_anchor: 0.000376616 },
        lbf_ft_min: { name: { singular: 'Pound-foot/minute', plural: 'Pound-foot/minute' }, to_anchor: 0.0225969 },
        lbf_ft_s: { name: { singular: 'Pound-foot/second', plural: 'Pound-foot/second' }, to_anchor: 1.35582 },
        erg_s: { name: { singular: 'Erg/second', plural: 'Ergs/second' }, to_anchor: 0.0000001 },
        kV_A: { name: { singular: 'Kilovolt ampere', plural: 'Kilovolt amperes' }, to_anchor: 1000 },
        V_A: { name: { singular: 'Volt ampere', plural: 'Volt amperes' }, to_anchor: 1 },
        N_m_s: { name: { singular: 'Newton meter/second', plural: 'Newton meters/second' }, to_anchor: 1 },
        J_s: { name: { singular: 'Joule/second', plural: 'Joules/second' }, to_anchor: 1 },
        EJ_s: { name: { singular: 'Exajoule/second', plural: 'Exajoules/second' }, to_anchor: 1e18 },
        PJ_s: { name: { singular: 'Petajoule/second', plural: 'Petajoules/second' }, to_anchor: 1e15 },
        TJ_s: { name: { singular: 'Terajoule/second', plural: 'Terajoules/second' }, to_anchor: 1e12 },
        GJ_s: { name: { singular: 'Gigajoule/second', plural: 'Gigajoules/second' }, to_anchor: 1e9 },
        MJ_s: { name: { singular: 'Megajoule/second', plural: 'Megajoules/second' }, to_anchor: 1e6 },
        kJ_s: { name: { singular: 'Kilojoule/second', plural: 'Kilojoules/second' }, to_anchor: 1000 },
        hJ_s: { name: { singular: 'Hectojoule/second', plural: 'Hectojoules/second' }, to_anchor: 100 },
        daJ_s: { name: { singular: 'Dekajoule/second', plural: 'Dekajoules/second' }, to_anchor: 10 },
        dJ_s: { name: { singular: 'Decijoule/second', plural: 'Decijoules/second' }, to_anchor: 0.1 },
        cJ_s: { name: { singular: 'Centijoule/second', plural: 'Centijoules/second' }, to_anchor: 0.01 },
        mJ_s: { name: { singular: 'Millijoule/second', plural: 'Millijoules/second' }, to_anchor: 0.001 },
        µJ_s: { name: { singular: 'Microjoule/second', plural: 'Microjoules/second' }, to_anchor: 1e-6 },
        nJ_s: { name: { singular: 'Nanojoule/second', plural: 'Nanojoules/second' }, to_anchor: 1e-9 },
        pJ_s: { name: { singular: 'Picojoule/second', plural: 'Picojoules/second' }, to_anchor: 1e-12 },
        fJ_s: { name: { singular: 'Femtojoule/second', plural: 'Femtojoules/second' }, to_anchor: 1e-15 },
        aJ_s: { name: { singular: 'Attojoule/second', plural: 'Attojoules/second' }, to_anchor: 1e-18 },
        J_h: { name: { singular: 'Joule/hour', plural: 'Joules/hour' }, to_anchor: 0.000277778 },
        J_min: { name: { singular: 'Joule/minute', plural: 'Joules/minute' }, to_anchor: 0.0166667 },
        kJ_h: { name: { singular: 'Kilojoule/hour', plural: 'Kilojoules/hour' }, to_anchor: 0.277778 },
        kJ_min: { name: { singular: 'Kilojoule/minute', plural: 'Kilojoules/minute' }, to_anchor: 16.6667 },
    },
    _anchors: {
        metric: { unit: 'W', ratio: 1 },
        imperial: { unit: 'hp', ratio: 1 / 745.7 }
    }
};

export default power;
