const pressure = {
    metric: {
        Pa: { name: { singular: 'Pascal', plural: 'Pascals' }, to_anchor: 1 },
        kPa: { name: { singular: 'Kilopascal', plural: 'Kilopascals' }, to_anchor: 1000 },
        bar: { name: { singular: 'Bar', plural: 'Bars' }, to_anchor: 100000 },
        psi: { name: { singular: 'Psi', plural: 'Psi' }, to_anchor: 6894.76 },
        ksi: { name: { singular: 'Ksi', plural: 'Ksi' }, to_anchor: 6894760 },
        atm: { name: { singular: 'Standard atmosphere', plural: 'Standard atmospheres' }, to_anchor: 101325 },
        EPa: { name: { singular: 'Exapascal', plural: 'Exapascals' }, to_anchor: 1e18 },
        PPa: { name: { singular: 'Petapascal', plural: 'Petapascals' }, to_anchor: 1e15 },
        TPa: { name: { singular: 'Terapascal', plural: 'Terapascals' }, to_anchor: 1e12 },
        GPa: { name: { singular: 'Gigapascal', plural: 'Gigapascals' }, to_anchor: 1e9 },
        MPa: { name: { singular: 'Megapascal', plural: 'Megapascals' }, to_anchor: 1e6 },
        hPa: { name: { singular: 'Hectopascal', plural: 'Hectopascals' }, to_anchor: 100 },
        daPa: { name: { singular: 'Dekapascal', plural: 'Dekapascals' }, to_anchor: 10 },
        dPa: { name: { singular: 'Decipascal', plural: 'Decipascals' }, to_anchor: 0.1 },
        cPa: { name: { singular: 'Centipascal', plural: 'Centipascals' }, to_anchor: 0.01 },
        mPa: { name: { singular: 'Millipascal', plural: 'Millipascals' }, to_anchor: 0.001 },
        µPa: { name: { singular: 'Micropascal', plural: 'Micropascals' }, to_anchor: 1e-6 },
        nPa: { name: { singular: 'Nanopascal', plural: 'Nanopascals' }, to_anchor: 1e-9 },
        pPa: { name: { singular: 'Picopascal', plural: 'Picopascals' }, to_anchor: 1e-12 },
        fPa: { name: { singular: 'Femtopascal', plural: 'Femtopascals' }, to_anchor: 1e-15 },
        aPa: { name: { singular: 'Attopascal', plural: 'Attopascals' }, to_anchor: 1e-18 }
    },
    imperial: {
        N__pm2: { name: { singular: 'Newton/square meter', plural: 'Newtons/square meter' }, to_anchor: 1 },
        N__pcm2: { name: { singular: 'Newton/square centimeter', plural: 'Newtons/square centimeter' }, to_anchor: 10000 },
        N__pmm2: { name: { singular: 'Newton/square millimeter', plural: 'Newtons/square millimeter' }, to_anchor: 1000000 },
        kN__pm2: { name: { singular: 'Kilonewton/square meter', plural: 'Kilonewtons/square meter' }, to_anchor: 1000 },
        mbar: { name: { singular: 'Millibar', plural: 'Millibars' }, to_anchor: 100 },
        µbar: { name: { singular: 'Microbar', plural: 'Microbars' }, to_anchor: 0.1 },
        dyn__pcm2: { name: { singular: 'Dyne/square centimeter', plural: 'Dynes/square centimeter' }, to_anchor: 0.1 },
        kgf__pm2: { name: { singular: 'Kilogram-force/square meter', plural: 'Kilogram-forces/square meter' }, to_anchor: 9.80665 },
        kgf__pcm2: { name: { singular: 'Kilogram-force/square centimeter', plural: 'Kilogram-forces/square centimeter' }, to_anchor: 980665 },
        kgf__pmm2: { name: { singular: 'Kilogram-force/square millimeter', plural: 'Kilogram-forces/square millimeter' }, to_anchor: 980665000 },
        gf__pcm2: { name: { singular: 'Gram-force/square centimeter', plural: 'Gram-forces/square centimeter' }, to_anchor: 98.0665 },
        tf__psft: { name: { singular: 'Ton-force (short)/square foot', plural: 'Tons-force (short)/square foot' }, to_anchor: 47880.3 },
        tf__psin2: { name: { singular: 'Ton-force (short)/square inch', plural: 'Tons-force (short)/square inch' }, to_anchor: 6894757.29 },
        tf__plft: { name: { singular: 'Ton-force (long)/square foot', plural: 'Tons-force (long)/square foot' }, to_anchor: 42335.7 },
        tf__plin2: { name: { singular: 'Ton-force (long)/square inch', plural: 'Tons-force (long)/square inch' }, to_anchor: 6132330.98 },
        kipf__psin2: { name: { singular: 'Kip-force/square inch', plural: 'Kips-force/square inch' }, to_anchor: 6894757.29 },
        lbf__psft: { name: { singular: 'Pound-force/square foot', plural: 'Pounds-force/square foot' }, to_anchor: 47.8803 },
        lbf__psin2: { name: { singular: 'Pound-force/square inch', plural: 'Pounds-force/square inch' }, to_anchor: 6894.76 },
        pdl__psft: { name: { singular: 'Poundal/square foot', plural: 'Poundals/square foot' }, to_anchor: 1.48816 },
        Torr: { name: { singular: 'Torr', plural: 'Torr' }, to_anchor: 133.322 },
        cm_Hg_0C: { name: { singular: 'Centimeter mercury (0°C)', plural: 'Centimeters mercury (0°C)' }, to_anchor: 1333.22 },
        mm_Hg_0C: { name: { singular: 'Millimeter mercury (0°C)', plural: 'Millimeters mercury (0°C)' }, to_anchor: 133.322 },
        in_Hg_32F: { name: { singular: 'Inch mercury (32°F)', plural: 'Inches mercury (32°F)' }, to_anchor: 3386.39 },
        in_Hg_60F: { name: { singular: 'Inch mercury (60°F)', plural: 'Inches mercury (60°F)' }, to_anchor: 3376.85 },
        cm_H2O_4C: { name: { singular: 'Centimeter water (4°C)', plural: 'Centimeters water (4°C)' }, to_anchor: 98.0638 },
        mm_H2O_4C: { name: { singular: 'Millimeter water (4°C)', plural: 'Millimeters water (4°C)' }, to_anchor: 9.80638 },
        in_H2O_4C: { name: { singular: 'Inch water (4°C)', plural: 'Inches water (4°C)' }, to_anchor: 249.082 },
        ft_H2O_4C: { name: { singular: 'Foot water (4°C)', plural: 'Feet water (4°C)' }, to_anchor: 2988.98 },
        in_H2O_60F: { name: { singular: 'Inch water (60°F)', plural: 'Inches water (60°F)' }, to_anchor: 248.84 },
        ft_H2O_60F: { name: { singular: 'Foot water (60°F)', plural: 'Feet water (60°F)' }, to_anchor: 2986.12 },
        at: { name: { singular: 'Atmosphere technical', plural: 'Atmospheres technical' }, to_anchor: 98066.5 }
    },
    _anchors: {
        metric: { unit: 'Pa', ratio: 1 },
        imperial: { unit: 'N__pm2', ratio: 1 / 9.80665 }
    }
};

export default pressure;
